generatorName: delphi-whizaxe
outputDir: samples/server/vpos/delphi/whizaxe
inputSpec: ../api-vpos/api-vpos.yml
templateDir: modules/openapi-generator/src/main/resources/delphi-whizaxe
additionalProperties:
  hideGenerationTimestamp: "true"
  modelType: "properties"
  modelNamePrefix: ""
  modelFilenamePrefix: "ApiModel."
  generateAliasAsModel: "true"
  openApiSkipValidateSpec: "true"
  useModelsFullNamespace: "true"
  sanitizedParamPrefixToSkip: "x"
  